import jsPDF from 'jspdf'

interface ReportData {
  borrowerName: string
  phone: string
  pan: string
  occupation: string
  monthlyIncome: number
  loanAmount: number
  loanPurpose: string
  creditScore: number
  riskBand: string
  collateralValue: number
  assetType: string
  assetDescription: string
  assetCondition: string
  fraudFlags: string[]
  aiReport: string
  applicationId: string
  createdAt: string
}

export function generatePDFReport(data: ReportData) {
  const doc = new jsPDF()
  const pageW = doc.internal.pageSize.getWidth()
  let y = 20

  function addLine(text: string, fontSize = 11, bold = false, color = [0, 0, 0]) {
    doc.setFontSize(fontSize)
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.setTextColor(color[0], color[1], color[2])
    doc.text(text, 20, y)
    y += fontSize * 0.6
  }

  function addSection(title: string) {
    y += 4
    doc.setFillColor(240, 245, 255)
    doc.rect(15, y - 5, pageW - 30, 10, 'F')
    addLine(title, 12, true, [30, 64, 175])
    y += 4
  }

  function addDivider() {
    doc.setDrawColor(220, 220, 220)
    doc.line(15, y, pageW - 15, y)
    y += 6
  }

  function addKeyValue(key: string, value: string) {
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 100, 100)
    doc.text(key + ':', 20, y)
    doc.setTextColor(0, 0, 0)
    doc.setFont('helvetica', 'bold')
    doc.text(value, 100, y)
    y += 7
  }

  function checkPageBreak() {
    if (y > 270) {
      doc.addPage()
      y = 20
    }
  }

  // Header
  doc.setFillColor(30, 64, 175)
  doc.rect(0, 0, pageW, 35, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('LoanVerify', 20, 15)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Collateral Assessment & Credit Report', 20, 23)
  doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, pageW - 70, 23)
  y = 45

  // Score badge
  const scoreColor: [number, number, number] =
    data.creditScore >= 700 ? [34, 197, 94] :
    data.creditScore >= 500 ? [245, 158, 11] : [239, 68, 68]

  doc.setFillColor(...scoreColor)
  doc.roundedRect(pageW - 70, y - 8, 55, 20, 4, 4, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text(data.creditScore.toString(), pageW - 58, y + 6)
  doc.setFontSize(9)
  doc.text('Credit Score', pageW - 66, y - 1)

  // Application info
  addSection('Application Information')
  addKeyValue('Application ID', data.applicationId.slice(0, 8) + '...')
  addKeyValue('Date', new Date(data.createdAt).toLocaleDateString('en-IN', {
    day: 'numeric', month: 'long', year: 'numeric'
  }))
  addKeyValue('Loan Amount', `Rs. ${data.loanAmount.toLocaleString('en-IN')}`)
  addKeyValue('Purpose', data.loanPurpose)
  addKeyValue('Risk Band', data.riskBand.toUpperCase())
  addDivider()

  checkPageBreak()

  // Borrower details
  addSection('Borrower Details')
  addKeyValue('Full Name', data.borrowerName)
  addKeyValue('Phone', data.phone)
  addKeyValue('PAN', data.pan)
  addKeyValue('Occupation', data.occupation)
  addKeyValue('Monthly Income', `Rs. ${data.monthlyIncome?.toLocaleString('en-IN')}`)
  addDivider()

  checkPageBreak()

  // Collateral details
  addSection('Collateral Assessment')
  addKeyValue('Asset Type', data.assetType)
  addKeyValue('Description', data.assetDescription)
  addKeyValue('Condition', data.assetCondition?.toUpperCase())
  addKeyValue('Estimated Value', `Rs. ${data.collateralValue?.toLocaleString('en-IN')}`)
  addKeyValue('Coverage Ratio',
    `${Math.round((data.collateralValue / data.loanAmount) * 100)}%`)
  addDivider()

  checkPageBreak()

  // Fraud flags
  if (data.fraudFlags?.length > 0) {
    addSection('Fraud Flags Detected')
    doc.setFillColor(254, 226, 226)
    doc.rect(15, y - 2, pageW - 30, data.fraudFlags.length * 8 + 8, 'F')
    data.fraudFlags.forEach(flag => {
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(185, 28, 28)
      doc.text(`! ${flag}`, 22, y + 4)
      y += 8
    })
    y += 4
    addDivider()
  }

  checkPageBreak()

  // AI Report
  addSection('AI Assessment Report')
  if (data.aiReport) {
    const lines = doc.splitTextToSize(data.aiReport, pageW - 40)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(40, 40, 40)
    lines.forEach((line: string) => {
      checkPageBreak()
      doc.text(line, 20, y)
      y += 6
    })
  }

  addDivider()

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 15
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text(
    'This report is auto-generated by LoanVerify AI. Subject to manual review.',
    pageW / 2, footerY, { align: 'center' }
  )

  doc.save(`LoanVerify_Report_${data.borrowerName.replace(' ', '_')}.pdf`)
}